### PR TITLE
Add support for nested collections like `map[map[[integer]]]`

### PR DESCRIPTION
**Pull request by NKorchagin**

### CODE REVIEW

**Comment by emaloney** [comment]
Looks reasonable to me. However, we'll need to test this change on the `swift-4` branch in Xcode 9 to make sure that it compiles on Swift 4 and generated valid Swift 4 code.

**Comment by NKorchagin** [comment]
Can I merge it to master for now? I have no new Xcode and Swift 4 anyway...

**Comment by emaloney** [comment]
Then I'd rather you hold off on merging this until we've gotten all our Swift 4 branches merged down to master. I've already got the Swift 4 branches working and I'd rather not get stuck with the work of having to re-port & re-test everything in Swift 4.

**Comment by NKorchagin** [comment]
Merged with Swift 4, everything is OK

**Pull request merged**
